server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: application-logs
    static_configs:
      - targets:
          - backend
        labels:
          job: application-logs
          __path__: /app/logs/*.log
    relabel_configs:
      - source_labels: [ '__path__' ]
        regex: '.*prometheus.*'
        action: drop